### PR TITLE
[Integration with AzureMonitor]: Adding changes to send metrics for Standingby servers to AppInsights.

### PR DESCRIPTION
**Pull request by rangira**
The PR addresses  the issue https://github.com/PlayFab/thundernetes/issues/383

### CODE REVIEW

**Comment by dgkanatsios** [comment]
hey @rangira, thanks for the PR! Ideally, we would not want to have product specific code inside Thundernetes. Any chance we can have Azure Monitor grab the already existing Prometheus metrics? If this is not possible, we can always have an external component on the ThundernetesContrib repository: https://github.com/PlayFab/thundernetescontrib

Thanks again for the contribution and apologies for the inconvenience!

**Comment by dgkanatsios** [comment]
Would this work, for example? https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-prometheus-integration

**Comment by rangira** [comment]
@dgkanatsios Thank you for sharing that. Could you please help me understand what are referring to when you say "product specific code". Are you referring to azure sdk for appinsights? Should it not be imported?

**Comment by dgkanatsios** [comment]
Yeah, the "AppInsights" code, exactly. At this point, we want to have these available as "extensions", hence the existence of the "ThundernetesContrib" repository as we want the Thundernetes core code base to be as lean as possible. Apologies again for the inconvenience and thanks for understanding, lets us know if you have any more questions!

**Comment by dgkanatsios** [comment]
ping @rangira, any help needed? Appreciate all the hard work!

**Comment by dgkanatsios** [comment]
Closing because of inactivity, feel free to reopen if needed. Thanks!

**Pull request closed without merging**
